config/routes.rb
Rails.application.routes.draw do
  root "links#index"
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  resources :links do
    resources :votes
    resources :comments
  end

  get 'users/profile' => 'users#profile', :as => :profile
  get 'users/links' => 'users#user_links', :as => :user_links
  get 'users/hearts' => 'users#user_votes', :as => :user_votes
  get 'users/comments' => 'users#user_comments', :as => :user_comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :votes

  validates :url, format: {with: /\.(png|jpg|gif|jpeg)\Z/i}

  after_destroy do
    Vote.destroy_all(link_id: self.id)
    Comment.destroy_all(link_id: self.id)
  end

  def total_votes
    self.votes.inject(0) { |sum, vote| sum + vote.value }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  has_many :comments
  has_many :votes

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.nickname = auth["info"]["nickname"]
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :link
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate, only: [:create]

  def new
    unless session[:user_id].nil?
      @comment = Comment.new
      @action = "create"
    else
      redirect_to root_path, notice: "Please login."
    end
  end

  def create
    Comment.create(comment_params)
    Comment.last.update(user_id: session[:user_id])

    redirect_to links_path(anchor: "link_#{params[:link_id]}")
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy

    redirect_to links_path
  end

  private

  def comment_params
    comment = params.require(:comment).permit(:comment)
    comment.merge(params.permit(:link_id))
  end

  def authenticate
    redirect_to root_url, notice: "Please login." if current_user.nil?
  end
end

app/controllers/links_controller.rb
require 'will_paginate/array'

class LinksController < ApplicationController
  before_filter :authenticate, only: [:new, :edit]
  before_filter :populate_comment_form, only: [:index, :show]

  def index
    if params[:sort] == "hearts"
      links = Link.all.sort_by { |link| link.total_votes }.reverse
    else
      links = Link.all.reverse
    end
    @links = links.paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
    @action = "create"
    @what = "Add"
  end

  def create
    @link = Link.new(link_params)
    @action = "create"
    @what = "Add"
    if @link.save
      @link.update(user_id: session[:user_id])
      redirect_to links_path
    else
      flash[:alert] = "Invalid. URL ending must be PNG, JPG, JPEG or GIF."
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
    @action = "update"
    @what = "Update"

    render :new
  end

  def update
    @link = Link.find(params[:id])
    @link.attributes = link_params
    @action = "update"
    @what = "Update"
    if @link.save
      redirect_to links_path
    else
      flash[:alert] = "Invalid. URL ending must be PNG, JPG, JPEG or GIF."
      render :new
    end
  end

  def destroy
    link = Link.find(params[:id])
    link.destroy

    redirect_to links_path
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end

  def authenticate
    redirect_to root_url, notice: "Please login." if current_user.nil?
  end

  def populate_comment_form
    ## for comment form
    @comment = Comment.new
    @action = "create"
    ##
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    if user.nickname.nil?
      user.nickname = auth["info"]["nickname"]
      user.save
    end
    session[:user_id] = user.id
    redirect_to links_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :populate_comment_form, only: [:user_links, :user_votes, :user_comments]

  def profile
    @user = current_user
    @links = current_user.links
    @comments = current_user.comments
    @votes = current_user.votes.where(value: 1)
  end

  def user_links
    if params[:sort] == "hearts"
      links = current_user.links.sort_by { |link| link.total_votes }.reverse
    else
      links = current_user.links.reverse
    end
    @links = links.paginate(:page => params[:page], :per_page => 5)
    render :template => 'links/index'
  end

  def user_votes
    votes = current_user.votes
    link_ids = []
    votes.each do |vote|
      link_ids.push(vote.link_id)
    end
    if params[:sort] == "hearts"
      links = Link.find(link_ids).sort_by { |link| link.total_votes }.reverse
    else
      links = Link.find(link_ids).reverse
    end
    @links = links.paginate(:page => params[:page], :per_page => 5)
    render :template => 'links/index'
  end

  def user_comments
    comments = current_user.comments
    link_ids = []
    comments.each do |comment|
      link_ids.push(comment.link_id)
    end
    if params[:sort] == "hearts"
      links = Link.find(link_ids).sort_by { |link| link.total_votes }.reverse
    else
      links = Link.find(link_ids).reverse
    end
    @links = links.paginate(:page => params[:page], :per_page => 5)
    render :template => 'links/index'
  end

  private

  def populate_comment_form
    ## for comment form
    @comment = Comment.new
    @action = "create"
    ##
  end

end

app/controllers/votes_controller.rb
 class VotesController < ApplicationController
  before_filter :authenticate, only: [:create, :update]

  def create
    Vote.create({value: 1, user_id: session[:user_id], link_id: params[:link_id]})

    redirect_to links_path(anchor: "link_#{params[:link_id]}")
  end

  def update
    vote = Vote.find(params[:id])
    if vote.value == 1
      vote.update(value: 0)
    elsif vote.value == 0
      vote.update(value: 1)
    end

    redirect_to links_path(anchor: "link_#{params[:link_id]}")
  end

  private

  def authenticate
    redirect_to root_url, notice: "Please login." if current_user.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_new.html.erb
<%= form_for @comment, action: :create, url: link_comments_path(@link_id) do |f| %>
  <%= f.text_field :comment, required: true, placeholder: "Comment on the cuteness!" %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Adorables", root_path %></div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "ADD A LINK", new_link_path if current_user %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SORT<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Most Hearted", links_path(sort: "hearts") %>
            </li>
            <li>
              <%= link_to "Newest", links_path %>
            </li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="navbar-text">
          <% if current_user %>
            <% if !current_user.name.nil? %>
              <%= link_to current_user.name, profile_path(current_user), id: "view-profile" %>
            <% elsif !current_user.nickname.nil? %>
              <%= current_user.nickname %>
            <% end %>
          <% end %>
          <% if flash[:notice] %>
          <div class="flash">
            <%= flash.notice %>
          </div>
          <% end %>
        </li>
        <li>
          <% if current_user %>
            <%= link_to "LOGOUT", signout_path %>
          <% else %>
            <%= link_to "/auth/github" do %>
              <%= fa_icon("github lg") %> LOG IN WITH GITHUB
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adorables</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'cat-favicon.png' %>
</head>
<body>
  <%= render 'layouts/header' unless @disable_nav %>

  <div class="wrapper">
    <div class="container-fluid">

    <%= yield %>

    </div>
  </div>
</body>
</html>

app/views/links/index.html.erb
<% unless @links.empty? %>
  <div class="row">
    <% @links.each do |link| %>
    <div id=<%= "link_#{link.id}" %> class="panel panel-default">
      <div class="panel-heading">
        <h6 class="panel-title">
          Submitted <%= time_ago_in_words(link.created_at) %> ago
          <% if !link.user.name.nil? %>
            by <%= link.user.name %>
          <% elsif !link.user.nickname.nil? %>
            by <%= link.user.nickname %>
          <% else %>
            by Anonymous
          <% end %>
        </h6>
      </div>
      <%= link_to(edit_link_path(link), title: "Edit", class: "btn pull-right") { fa_icon("pencil-square-o lg") } if link.user_id == session[:user_id] %>
      <div class="panel-body">
        <div class="col-sm-12">
          <%# link_to(image_tag(link.url, class: "img-responsive"), link_path(link))%>
          <%= image_tag(link.url, class: "img-responsive") %>
          <div class="caption">
            <div class="comments">
              <div><%= link.total_votes %> hearts</div>
              <% if link.title %>
                <h4><%= link.title %></h4>
              <% end %>
              <% link.comments.each do |comment| %>
                <% if !comment.user.name.nil? %>
                  <%= comment.user.name %>:
                <% elsif !comment.user.nickname.nil? %>
                  <span><%= comment.user.nickname %>:</span>
                <% else %>
                  Anonymous:
                <% end %>
                <%= comment.comment %>
                <%= link_to(link_comment_path(link, comment), method: :delete, class: "pull-right") { fa_icon("times") } if comment.user.id == session[:user_id]%>
                <br>
              <% end %>
            </div>
            <% unless session[:user_id].nil? || link.votes.empty? %>
              <% unless link.votes.where(user_id: session[:user_id]).empty? %>
                <% if link.votes.where(user_id: session[:user_id]).first.value == 1 %>
                  <%= link_to(link_vote_path(link, link.votes.where(user_id: session[:user_id]).first), method: :patch, class: "btn pull-left") { fa_icon("heart 2x") } %>
                <% else %>
                  <%= link_to(link_vote_path(link, link.votes.where(user_id: session[:user_id]).first), method: :patch, class: "btn pull-left") { fa_icon("heart-o 2x") } %>
                <% end %>
              <% else %>
                <%= link_to(link_votes_path(link), method: :post, class: "btn pull-left") { fa_icon("heart-o 2x") } %>
              <% end %>
            <% else %>
              <%= link_to(link_votes_path(link), method: :post, class: "btn pull-left") { fa_icon("heart-o 2x") } %>
            <% end %>
            <%= render "/comments/new", :@link_id => link.id%>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <div>
<% end %>

<%= will_paginate @links %>

app/views/links/new.html.erb
<%= form_for @link, url: { action: @action } do |f| %>
<fieldset class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.label :url, "URL" %>
  <%= f.url_field :url, required: true, class: "form-control" %>
  <% if flash[:alert] %>
    <%= flash.alert %>
  <% end %>
  <br>
  <%= f.submit @what + " Link", class: "btn btn-primary btn-block" %>
<% end %>
</fieldset>
<%= button_to("Delete Link", link_path(@link), method: "delete", onclick: "return confirm('Are you sure?')", title: "Delete", class: "btn btn-primary btn-block") if !@link.id.nil? %>

app/views/links/show.html.erb
<div class="row">
  <div id=<%= "link_#{@link.id}" %> class="panel panel-default">
    <div class="panel-heading">
      <h6 class="panel-title">
        Submitted <%= time_ago_in_words(@link.created_at) %> ago
        <% if !@link.user.name.nil? %>
          by <%= @link.user.name %>
        <% elsif !@link.user.nickname.nil? %>
          by <%= @link.user.nickname %>
        <% else %>
          by Anonymous
        <% end %>
      </h6>
    </div>
    <%= link_to(edit_link_path(@link), title: "Edit", class: "btn pull-right") { fa_icon("pencil-square-o lg") } if @link.user_id == session[:user_id] %>
    <div class="panel-body">
      <div class="col-sm-12">
        <%# link_to(image_tag(link.url, class: "img-responsive"), link_path(link))%>
        <%= image_tag(@link.url, class: "img-responsive") %>
        <div class="caption">
          <div class="comments">
            <div><%= @link.total_votes %> hearts</div>
            <% if @link.title %>
              <h4><%= @link.title %></h4>
            <% end %>
            <% @link.comments.each do |comment| %>
              <% if !comment.user.name.nil? %>
                <%= comment.user.name %>:
              <% elsif !comment.user.nickname.nil? %>
                <span><%= comment.user.nickname %>:</span>
              <% else %>
                Anonymous:
              <% end %>
              <%= comment.comment %>
              <%= link_to(link_comment_path(@link, comment), method: :delete, class: "pull-right") { fa_icon("times") } if comment.user.id == session[:user_id]%>
              <br>
            <% end %>
          </div>
          <% unless session[:user_id].nil? || @link.votes.empty? %>
            <% unless @link.votes.where(user_id: session[:user_id]).empty? %>
              <% if @link.votes.where(user_id: session[:user_id]).first.value == 1 %>
                <%= link_to(link_vote_path(@link, @link.votes.where(user_id: session[:user_id]).first), method: :patch, class: "btn pull-left") { fa_icon("heart 2x") } %>
              <% else %>
                <%= link_to(link_vote_path(@link, @link.votes.where(user_id: session[:user_id]).first), method: :patch, class: "btn pull-left") { fa_icon("heart-o 2x") } %>
              <% end %>
            <% else %>
              <%= link_to(link_votes_path(@link), method: :post, class: "btn pull-left") { fa_icon("heart-o 2x") } %>
            <% end %>
          <% else %>
            <%= link_to(link_votes_path(@link), method: :post, class: "btn pull-left") { fa_icon("heart-o 2x") } %>
          <% end %>
          <%= render "/comments/new", :@link_id => @link.id%>
        </div>
      </div>
    </div>
  </div>
<div>

app/views/users/profile.html.erb
<div class="row">
  <h1>Hello, <%= @user.name %>!</h1>
</div>
<div class="row">
  <h3>Your Adorables</h3>
  <% if @links.empty? %>
    You haven't posted anything yet! Would you like to <%= link_to "post something adorable", new_link_path %>?
  <% elsif @links.count == 1 %>
    You've posted <%= @links.count %> adorable thing! <%= link_to "See your link", link_path(@links.first.id) %>
  <% else %>
    You've posted <%= @links.count %> adorable things! <%= link_to "See all your links", user_links_path %>
  <% end %>
</div>
<div class="row">
  <h3>Your Favorites</h3>
  <% if @votes.empty? %>
    You haven't favorited anything yet! <%= link_to "Browse adorables", root_path %>
  <% elsif @votes.count == 1 %>
    You've favorited <%= @votes.count %> adorable thing! <%= link_to "See your favorite", link_path(@votes.first.link_id) %>
  <% else %>
    You've favorited <%= @votes.count %> adorable things! <%= link_to "See all your favorites", user_votes_path %>
  <% end %>
</div>
<div class="row">
  <h3>Your Comments</h3>
  <% if @comments.empty? %>
    You haven't commented on anything yet! <%= link_to "Browse adorables", root_path %> (maybe add some random suggestions here?)
  <% elsif @comments.count == 1 %>
    You've made a comment on an adorable thing! <%= link_to "See the link you've commented on", link_path(@comments.first.link_id) %>
  <% else %>
    You've made <%= @comments.count %> comments on adorable things! <%= link_to "See all links you've commented on", user_comments_path %>
  <% end %>
</div>
<div class="row">
  <h3>Recently Hearted</h3>
</div>